#lang racket
(provide convert-complex-datum)
(require "utils.rkt")
;<exp> ::= (quote <datum>)
;       |  <uvar>
;       |  (if <exp> <exp> <exp>)
;       |  (set! <uvar> <exp>)
;       |  (begin <exp>+)
;       |  (lambda (<uvar>*) <exp>)
;       |  (let ((<uvar> <exp>)*) <exp>)
;       |  (letrec ((<uvar> <exp>)*) <exp>)
;       |  (primapp <prim> <exp>*)
;       |  (procapp <exp> <exp>*)
;<uvar> ::= (uvar <symbol> <integer>)
(define (convert-complex-datum exp)
  (define bindings '())
  (define (convert-datum x)
    (cond ((pair? x) (list 'primapp 'cons (convert-datum (car x)) (convert-datum (cdr x))))
          ((vector? x)
           (let ((l (vector-length x)))
             (if (= l 0)
                 '(primapp make-vector '0)
                 (let ((t (unique-symbol 't)))
                   `(let ((,t (primapp make-vector (quote ,l))))
                      ,(let loop ((i l) (e* (cons t '())))
                         (if (= i 0)
                             (cons 'begin e*)
                             (let ((i (- i 1)))
                               (loop i
                                     (cons
                                      `(primapp vector-set! ,t (quote ,i)
                                                ,(convert-datum (vector-ref x i)))
                                      e*))))))))))
          (else `(quote ,x))))
  (define (add-binding! datum)
    (define t (unique-symbol 't))
    (define d (convert-datum datum))
    (push! (list t d) bindings)
    t)
  (define (convert exp)
    (match exp
      ((quote ,d) (if (or (pair? d) (vector? d))
                      (add-binding! d)
                      exp))
      ((uvar ,name ,id) exp)
      ((if ,q ,a ,e) `(if ,(convert q)
                          ,(convert a)
                          ,(convert e)))
      ((set! ,uvar ,exp) `(set! ,uvar ,(convert exp)))
      ((begin . ,exps) (cons 'begin (map convert exps)))
      ((lambda ,x* ,body) `(lambda ,x* ,(convert body)))
      ((let ,bds ,body)
       (: bds
          (lambda (x* e*)
            (let ((e* (map convert e*))
                  (body (convert body)))
              (Let x* e* body)))))
      ((letrec ,bds ,body)
       (: bds
          (lambda (x* e*)
            (let ((e* (map convert e*))
                  (body (convert body)))
              (Letrec x* e* body)))))
      ((primapp ,prim . ,exps)
       `(primapp ,prim . ,(map convert exps)))
      ((procapp . ,exps)
       `(procapp . ,(map convert exps)))))
  (let ((exp (convert exp)))
    (if (null? bindings)
        exp
        `(let ,bindings ,exp))))
;<exp> ::= (quote <immediate>)
;       |  <uvar>
;       |  (if <exp> <exp> <exp>)
;       |  (set! <uvar> <exp>)
;       |  (begin <exp>+)
;       |  (lambda (<uvar>*) <exp>)
;       |  (let ((<uvar> <exp>)*) <exp>)
;       |  (letrec ((<uvar> <exp>)*) <exp>)
;       |  (primapp <prim> <exp>*)
;       |  (procapp <exp> <exp>*)
;<immediate> ::= ()
;             |  <boolean>
;             |  <fixnum>