#lang racket
(provide uncover-assigned)
(require "utils.rkt")
;<exp> ::= (quote <immediate>)
;       |  <uvar>
;       |  (if <exp> <exp> <exp>)
;       |  (set! <uvar> <exp>)
;       |  (begin <exp>+)
;       |  (lambda (<uvar>*) <exp>)
;       |  (let ((<uvar> <exp>)*) <exp>)
;       |  (letrec ((<uvar> <exp>)*) <exp>)
;       |  (primapp <prim> <exp>*)
;       |  (procapp <exp> <exp>*)
;<immediate> ::= ()
;             |  <boolean>
;             |  <fixnum>
(define (uncover-assigned exp)
  (define (uncover-exps exps)
    (if (null? exps)
        (values '() '())
        (let-values (((a u*) (uncover (car exps)))
                     ((d v*) (uncover-exps (cdr exps))))
          (values (cons a d) (U u* v*)))))
  (define (uncover exp)
    (match exp
      ((quote ,i) (values exp '()))
      ((uvar ,name ,id) (values exp '()))
      ((if ,q ,a ,e)
       (let-values (((q u*) (uncover q))
                    ((a v*) (uncover a))
                    ((e w*) (uncover e)))
         (values `(if ,q ,a ,e) (U u* (U v* w*)))))
      ((set! ,uvar ,exp)
       (let-values (((exp u*) (uncover exp)))
         (values `(set! ,uvar ,exp)
                 (set-cons uvar u*))))
      ((begin . ,exps)
       (let-values (((exps u*) (uncover-exps exps)))
         (values (cons 'begin exps) u*)))
      ((lambda ,x* ,body)
       (let-values (((body u*) (uncover body)))
         (values `(lambda ,x*
                    (assigned ,(I x* u*) ,body))
                 (D u* x*))))
      ((let ,bds ,body)
       (: bds
          (lambda (x* e*)
            (let-values (((e* u*0) (uncover-exps e*))
                         ((body u*1) (uncover body)))
              (values (Let x* e* `(assigned ,(I x* u*1) ,body))
                      (U u*0 (D u*1 x*)))))))
      ((letrec ,bds ,body)
       (: bds
          (lambda (x* e*)
            (let-values (((e* u*0) (uncover-exps e*))
                         ((body u*1) (uncover body)))
              (let ((u*2 (U u*0 u*1)))
                (values (Letrec x* e* `(assigned ,(I x* u*2) ,body))
                        (D u*2 x*)))))))
      ((primapp ,prim . ,exps)
       (let-values (((exps u*) (uncover-exps exps)))
         (values `(primapp ,prim . ,exps) u*)))
      ((procapp . ,exps)
       (let-values (((exps u*) (uncover-exps exps)))
         (values `(procapp . ,exps) u*)))))
  (let-values (((exp u*) (uncover exp)))
    (if (null? u*)
        exp
        (error 'uncover-assigned "unbound assigned variables ~s" u*))))